: COUNTER
  CREATE
  0 ,
  DOES>
    DUP
    @ SWAP
    1 SWAP
    +! ;

COUNTER FU
COUNTER BAR
COUNTER BAZ

: INCREMENT
  ." INCREMENT:" CR
  FU 0 = IF ." OK" CR THEN
  FU 1 = IF ." OK" CR THEN
  FU 2 = IF ." OK" CR THEN ;

: INDEPENDENT
  ." INDEPENDENT:" CR
  BAR 0 = IF ." OK" CR THEN
  BAR 1 = IF ." OK" CR THEN
  BAR 2 = IF ." OK" CR THEN
  BAZ 0 = IF ." OK" CR THEN
  BAZ 1 = IF ." OK" CR THEN ;

: TEST INCREMENT INDEPENDENT BYE ;

TEST
